### ISSUE TITLE
강의 수강 공석 count

### ISSUE THREAD

**Issue by jeongjaehyeok-edu** [jeongjaehyeok-edu/ks-web-jpa#2]
강의 공석을 표시하는 화면 lesson_count.html 에서

수강신청(course) 데이터가 없는 경우 강의 정보가 나타나지 않는 현상.

    사용자 정의 쿼리를 수정하면 해결가능하므로 수정할 예정.

**Comment by jeongjaehyeok-edu** [comment]
SELECT   LE.ID,
         LE.NAME,
         LE.QUOTA - DECODE(CNT_COURCE.CNT_LESSON, NULL, 0, CNT_COURCE.CNT_LESSON)
FROM     LESSON LE,
         (SELECT   LESSON.ID,
                   LESSON.NAME,
                   COUNT(LESSON.ID) AS CNT_LESSON
          FROM     COURSE,
                   LESSON
          WHERE    1 = 1 AND COURSE.LESSON_ID = LESSON.ID
          GROUP BY LESSON.ID,
                   LESSON.NAME) CNT_COURCE
WHERE    CNT_COURCE.ID(+) = LE.ID
ORDER BY LE.ID ASC;

오라클에서 쿼리를 작성해왔으나, 
JPA에서는 FROM절에서 서브쿼리가 불가능한 것 같다.........

**Comment by jeongjaehyeok-edu** [comment]
@Query(value = "SELECT DISTINCT  LE.id, " +
        "         LE.name, " +
        "         LE.quota " +
        "           -DECODE" +
        "           ( " +
        "                   (SELECT " +
        "                            COUNT(Lesson.id) " +
        "                   FROM     Cource, " +
        "                            Lesson " +
        "                   WHERE    1 = 1  " +
        "                        AND Cource.lesson_id = Lesson.id " +
        "                        AND CO.lesson_id = Lesson.id " +
        "                        AND LE.id = Lesson.id " +
        "                   GROUP BY Lesson.id, " +
        "                            Lesson.name), " +
        "                  NULL, 0, " +
        "                  (SELECT  " +
        "                            COUNT(Lesson.id) " +
        "                   FROM     Cource, " +
        "                            Lesson " +
        "                   WHERE    1 = 1 " +
        "                        AND Cource.lesson_id = Lesson.id " +
        "                        AND CO.lesson_id = Lesson.id " +
        "                        AND LE.id=Lesson.id " +
        "                   GROUP BY Lesson.id, " +
        "                            Lesson.name) " +
        "           ) " +
        "FROM     Lesson LE, " +
        "         Cource CO " +
        "ORDER BY LE.id ASC ",nativeQuery = true)

SELECT절에서는 FROM절과 다르게 서브쿼리가 가능하다고하여 작성했으나,
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "COURCE" not found;
테이블을 못찾는다. 이 DB는 대/소문자를 구분하는 것으로 알고있는데... 
왜 대문자로 Cource를 찾는건지 모르겠다.

조금 더 생각해보자.

**Comment by sigmadream** [comment]
JPA를 사용할 경우 사용자 정의 쿼리를 작성하지 않아도 가능합니다. 데이터베이스에서 해결하지 말고, 객체(Course, Lesson 등) 관점에서 생각해보세요. 사용자 정의 쿼리를 사용하지 않아도 해결 가능합니다.

**Comment by jeongjaehyeok-edu** [comment]
> JPA를 사용할 경우 사용자 정의 쿼리를 작성하지 않아도 가능합니다. 데이터베이스에서 해결하지 말고, 객체(Course, Lesson 등) 관점에서 생각해보세요. 사용자 정의 쿼리를 사용하지 않아도 해결 가능합니다.

감사합니다!

**Comment by jeongjaehyeok-edu** [comment]
사용자 작성 쿼리는 가장 많이 구현된 상태로 올려두고,
새로운 페이지에서 수강현황을 작성하였습니다.

우선순위는
기능구현>>>>>>원본데이터 지키기>>원본데이터손실(수강신청시 수강인원 조정)>>>>>포기
입니다.
